// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEWXXx0OyJNM8YjhQz0gi3_mBWchLPfg0',
    appId: '1:760743097542:web:cd0f23d0a5b03b17aad3c7',
    messagingSenderId: '760743097542',
    projectId: 'flutter-firebase-example-22fcf',
    authDomain: 'flutter-firebase-example-22fcf.firebaseapp.com',
    storageBucket: 'flutter-firebase-example-22fcf.appspot.com',
    measurementId: 'G-S1XKC9WDRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHbaBpGvGUD0iCjtw4xbeFwVNCTsX8YGs',
    appId: '1:760743097542:android:108190e19d3cfc82aad3c7',
    messagingSenderId: '760743097542',
    projectId: 'flutter-firebase-example-22fcf',
    storageBucket: 'flutter-firebase-example-22fcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOteUgtUNXn1o8C4b4o4n8TF6o0WRbFAw',
    appId: '1:760743097542:ios:376dff9981a93026aad3c7',
    messagingSenderId: '760743097542',
    projectId: 'flutter-firebase-example-22fcf',
    storageBucket: 'flutter-firebase-example-22fcf.appspot.com',
    iosClientId: '760743097542-l2cfcio6n9pdi4hb1jn1qpia3uv1h1d7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOteUgtUNXn1o8C4b4o4n8TF6o0WRbFAw',
    appId: '1:760743097542:ios:376dff9981a93026aad3c7',
    messagingSenderId: '760743097542',
    projectId: 'flutter-firebase-example-22fcf',
    storageBucket: 'flutter-firebase-example-22fcf.appspot.com',
    iosClientId: '760743097542-l2cfcio6n9pdi4hb1jn1qpia3uv1h1d7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseExample',
  );
}
